"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['BillsMazeAdventure.py']
DATA_FILES = ['tiles/map-dirt.gif',
 'tiles/map-finish.gif',
 'tiles/map-start.gif',
 'tiles/map-stone.gif',
 'character/Bill-Back.gif',
 'character/Bill-Front.gif',
 'character/Bill-Left.gif',
 'character/Bill-Right.gif']
OPTIONS = {'argv_emulation': True,
 'iconfile': '/Users/paulmartin/src/108/icons/Icon.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
